"""Render the staging verification report to docs/STAGING.md.

Same contract as `scripts/eval_retrieval.py`: the numbers are generated from
the live database on every run, and everything below `ANALYSIS_MARKER` is
hand-written and survives a regeneration. A published number nobody can
reproduce is a claim; this one is a command.
"""

from __future__ import annotations

from datetime import UTC, datetime
from pathlib import Path
from typing import Any

import asyncpg

from staging.gates import GRAIN, GateResult

ANALYSIS_MARKER = "<!-- hand-written analysis below; preserved across re-runs -->"

REPORT_RELPATH = Path("docs") / "STAGING.md"


async def inventory(pool: asyncpg.Pool) -> list[dict[str, Any]]:
    """Row counts, partitions and on-disk size for every staged table."""
    rows: list[dict[str, Any]] = []
    async with pool.acquire() as conn:
        for table, grain in GRAIN.items():
            exists = await conn.fetchval("SELECT to_regclass($1) IS NOT NULL", f"staging.{table}")
            if not exists:
                continue
            key = grain.key
            partition = key[0] if key[0] in ("quarter", "snapshot") else None
            count = int(await conn.fetchval(f"SELECT count(*) FROM staging.{table}"))
            partitions: list[str] = []
            if partition:
                partitions = [
                    str(r[0])
                    for r in await conn.fetch(
                        f"SELECT DISTINCT {partition} FROM staging.{table} ORDER BY {partition}"
                    )
                ]
            size = await conn.fetchval(
                "SELECT pg_size_pretty(pg_total_relation_size($1))", f"staging.{table}"
            )
            rows.append(
                {
                    "table": table,
                    "grain": " + ".join(key),
                    "unique": grain.unique,
                    "rows": count,
                    "partitions": partitions,
                    "size": size,
                }
            )
    return rows


def _fmt(n: Any) -> str:
    return f"{n:,}" if isinstance(n, int) else str(n)


def render(
    results: list[GateResult],
    precision: list[dict[str, Any]],
    tables: list[dict[str, Any]],
    carryover: str = "",
) -> str:
    generated = datetime.now(UTC).strftime("%Y-%m-%d")
    total_rows = sum(t["rows"] for t in tables)
    passed = all(r.passed for r in results)

    lines = [
        "# Relational staging — load and verification report",
        "",
        f"_Generated by `python -m staging gates` on {generated}. "
        f"{len(tables)} tables, {total_rows:,} rows._",
        "",
        "The `documents` table holds one embedded row per thing the MCP tools can cite, with",
        "each source's detail in a JSONB payload. That is the right shape for retrieval and the",
        "wrong shape for analysis: no joins, no declared grain, no per-partition integrity. This",
        "layer is the other half — the upstream relational files loaded as tables, beside the",
        "document store rather than instead of it.",
        "",
        "## Gates",
        "",
        "Every gate is written to return rows only when something is wrong.",
        "",
        "| Gate | Checks | Rows checked | Result |",
        "|---|---|---|---|",
    ]
    for result in results:
        verdict = "pass" if result.passed else f"**FAIL** ({len(result.failures)} rows)"
        lines.append(
            f"| `{result.name}` | {result.description} | {result.rows_checked:,} | {verdict} |"
        )

    lines += ["", f"**Overall: {'all gates pass' if passed else 'GATES FAILING'}.**", ""]

    for result in results:
        if result.passed:
            continue
        lines += [f"### `{result.name}` failures", ""]
        for row in result.failures[:20]:
            lines.append(f"- `{row}`")
        if len(result.failures) > 20:
            lines.append(f"- …and {len(result.failures) - 20} more")
        lines.append("")

    # --- what is loaded ----------------------------------------------------
    lines += [
        "## What is loaded",
        "",
        "| Table | Grain (one row per …) | Rows | Partitions | Size |",
        "|---|---|---:|---|---:|",
    ]
    for table in tables:
        partitions = ", ".join(table["partitions"]) if table["partitions"] else "—"
        lines.append(
            f"| `staging.{table['table']}` | {table['grain']} | {table['rows']:,} "
            f"| {partitions} | {table['size']} |"
        )
    lines.append("")

    # --- grain detail ------------------------------------------------------
    grain = next((r for r in results if r.name == "grain"), None)
    if grain and grain.detail:
        lines += [
            "### Grain proof",
            "",
            "A table is only safe to join once you know whether its key identifies a row. Keys",
            "marked **unique** must not repeat, and the gate fails if they do. The rest are *join*",
            "keys: they repeat by design, and what matters is the fan-out — rows per distinct key,",
            "and the worst single key. That multiplier is how far wrong a `count(*)` after a join",
            "would be.",
            "",
            "| Table | Declared key | Unique? | Rows | Distinct keys | Fan-out | Worst key |",
            "|---|---|---|---:|---:|---:|---:|",
        ]
        for entry in grain.detail:
            unique = "yes" if entry["unique"] else "no — join key"
            lines.append(
                f"| `{entry['table']}` | {entry['key']} | {unique} | {entry['rows']:,} "
                f"| {entry['distinct_keys']:,} | {entry['fan_out']:.2f}× "
                f"| {entry['worst_group']:,} |"
            )
        lines.append("")

        notes = [e for e in grain.detail if e["note"]]
        if notes:
            lines += ["Where the key is not an identity, and why:", ""]
            for entry in notes:
                lines.append(f"- `{entry['table']}` — {entry['note']}.")
            lines.append("")

        worst = max(
            (e for e in grain.detail if not e["unique"] and e["rows"]),
            key=lambda e: e["worst_group"],
            default=None,
        )
        if worst and worst["worst_group"] > 1:
            lines += [
                f"The sharpest case is `{worst['table']}`: one key accounts for "
                f"{worst['worst_group']:,} rows. Joining on it and counting rows would report "
                f"that many of what is really one thing. Counting distinct keys, or aggregating"
                " before the join, is the fix.",
                "",
            ]

    # --- dedup conservation ------------------------------------------------
    dedup = next((r for r in results if r.name == "dedup"), None)
    if dedup and dedup.detail:
        numbers = dedup.detail[0]
        kept = numbers.get("kept", 0)
        superseded = numbers.get("superseded", 0)
        with_caseid = numbers.get("with_caseid", 0)
        inflation = (with_caseid / kept) if kept else 0.0
        balanced_phrase = (
            "they balance" if kept + superseded == with_caseid else "THEY DO NOT BALANCE"
        )
        lines += [
            "## FAERS case-version dedup",
            "",
            "A FAERS case is reported once and amended afterwards, and each amendment ships as a",
            "new row in a later quarter. Counting rows therefore counts amendments, not events.",
            "The resolution rule is the FDA's: latest `fda_dt`, ties broken on the highest",
            "`primaryid`, then on the quarter — a total order, so the result is reproducible.",
            "",
            "| | |",
            "|---|---:|",
            f"| Demo rows loaded | {numbers.get('demo_rows', 0):,} |",
            f"| …carrying a case id | {with_caseid:,} |",
            f"| Distinct cases kept | {kept:,} |",
            f"| Versions superseded | {superseded:,} |",
            f"| Cases the FDA later deleted | {numbers.get('deleted_cases', 0):,} |",
            "",
            f"Kept + superseded = {kept + superseded:,}, against {with_caseid:,} demo rows",
            f"with a case id — {balanced_phrase}.",
            "Every row is either a surviving version or one it superseded; none is lost to the",
            "dedup and none is counted twice.",
            "",
            f"In practice the raw extract over-counts distinct cases by {inflation:.2f}×. An"
            " analysis that",
            "skips this step reports that much more adverse-event activity than was reported.",
            "",
        ]

    # --- partial dates -----------------------------------------------------
    if precision:
        lines += [
            "## Partial dates kept, not guessed",
            "",
            "FAERS date columns are variable-width: `20250326` is a day, `200906` a month with no",
            "day, `2009` a year. Padding the missing parts invents values that then cannot be",
            "told from observed ones. Each date lands as three columns instead — `*_raw`,",
            "`*_prec` and a real `DATE` populated only at day precision.",
            "",
            "| Column | Values present | Day | Month | Year | Invalid | Not day-precision |",
            "|---|---:|---:|---:|---:|---:|---:|",
        ]
        for entry in precision:
            lines.append(
                f"| `{entry['table']}.{entry['column']}` | {entry['present']:,} "
                f"| {entry['day']:,} | {entry['month']:,} | {entry['year']:,} "
                f"| {entry['invalid']:,} | {entry['partial_share']:.1%} |"
            )
        lines += [
            "",
            "The last column is what padding would have fabricated.",
            "",
        ]

    # --- rejects -----------------------------------------------------------
    rejects = next((r for r in results if r.name == "rejects"), None)
    if rejects:
        lines += [
            "## Rejected rows",
            "",
            "Both upstreams ship unquoted delimited text, so a delimiter inside a free-text field",
            "produces a row with more fields than the header declares and there is no escaping to",
            "undo it. Those lines are kept verbatim in `staging.load_reject` with their line",
            "numbers — never dropped, never force-fitted.",
            "",
        ]
        if rejects.detail:
            lines += [
                "| Source | Table | Rows read | Rejected | Rate | Reasons |",
                "|---|---|---:|---:|---:|---|",
            ]
            for entry in rejects.detail:
                lines.append(
                    f"| {entry['source']} | `{entry['table_name']}` | {entry['rows_read']:,} "
                    f"| {entry['rejected']:,} | {entry['reject_rate']:.4%} "
                    f"| {'; '.join(entry['reasons'])} |"
                )
        else:
            lines.append("No rejected rows in the current load.")
        lines.append("")

    # --- integrity ---------------------------------------------------------
    integrity = next((r for r in results if r.name == "integrity"), None)
    if integrity and integrity.detail:
        lines += [
            "## Cross-table integrity",
            "",
            "Child rows whose parent is missing, scoped to the child's own partition: a FAERS",
            "drug row belongs to the demo row in its own quarter, not to any quarter. Written as",
            "`NOT EXISTS` — a `LEFT JOIN` filtered in `WHERE` silently becomes an inner join and",
            "reports zero orphans whether or not there are any.",
            "",
            "An orphan is **explained** when the parent row was rejected at load time: that child",
            "was always going to point at nothing, and the reject lane says so by name. It is",
            "**unexplained** when the parent simply is not in the feed, which is an upstream",
            "inconsistency. Only unexplained orphans fail the gate.",
            "",
            "| Child | Parent | Join | Rows | Orphans | Explained by a reject | Unexplained |",
            "|---|---|---|---:|---:|---:|---:|",
        ]
        for entry in integrity.detail:
            lines.append(
                f"| `{entry['child']}` | `{entry['parent']}` | {entry['join']} "
                f"| {entry['rows']:,} | {entry['orphan_rows']:,} "
                f"| {entry['explained_rows']:,} | {entry['unexplained_rows']:,} |"
            )
        lines.append("")
        total_orphans = sum(e["orphan_rows"] for e in integrity.detail)
        total_explained = sum(e["explained_rows"] for e in integrity.detail)
        if total_orphans and total_explained == total_orphans:
            lines += [
                f"All {total_orphans:,} orphans trace back to a rejected parent row. The chain is",
                "visible end to end: an unescaped `|` inside a study title rejects that study, and",
                "its sponsors, conditions, interventions and sites are orphaned by exactly that",
                "study — same count, same keys. Nothing is referentially broken upstream.",
                "",
            ]

    lines += [
        "## What this does not show",
        "",
        "- **Not a pharmacovigilance signal.** FAERS reports are voluntary, unverified and",
        "  duplicated across reporters; a case being present says someone reported it, not that a",
        "  drug caused it. Nothing here computes a disproportionality statistic, and the counts",
        "  cannot be used as incidence rates.",
        "- **Point-in-time.** Both sources are pinned archives. The numbers above describe the",
        "  loaded partitions, not the current state of either registry.",
        "- **A documented column subset.** `aact_studies` keeps 31 of `studies.txt`'s 71 columns;",
        "  the rest are result-reporting and IPD-sharing metadata nothing here joins on.",
        "- **Gates, not profiling.** They prove keys, conservation and referential integrity.",
        "  They say nothing about whether a value is clinically plausible.",
        "",
        "Re-run with `python -m staging gates` after any load; every number above comes from the",
        "database at the time it ran.",
        "",
        ANALYSIS_MARKER,
        "",
    ]

    body = "\n".join(lines)
    return body + (carryover.strip() + "\n" if carryover.strip() else "")


def write(
    root: Path,
    results: list[GateResult],
    precision: list[dict[str, Any]],
    tables: list[dict[str, Any]],
) -> Path:
    """Write docs/STAGING.md, preserving any hand-written analysis section."""
    path = root / REPORT_RELPATH
    carryover = ""
    if path.exists():
        previous = path.read_text(encoding="utf-8")
        if ANALYSIS_MARKER in previous:
            carryover = previous.split(ANALYSIS_MARKER, 1)[1]
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(render(results, precision, tables, carryover), encoding="utf-8")
    return path
